/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.plan.docente.web.util;

import co.com.plan.docente.vo.HorarioProfesorVO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jorge Montoya
 */
public class Util {

    public static final List<HorarioProfesorVO> listaHorario() {

        List<HorarioProfesorVO> horarios = new ArrayList<>();
        HorarioProfesorVO horarioAux = new HorarioProfesorVO();

        try {
            horarioAux.setDiaHora("[NINGUNO]");
            horarioAux.setIntencidadSemanal(0);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-6am-8am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-8am-10am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-10am-12pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-2pm-4pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-4pm-6pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-6pm-8pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-8pm-10pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-6am-8am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-8am-10am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-10am-12pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-2pm-4pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-4pm-6pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-6pm-8pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-8pm-10pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-6am-8am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-8am-10am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-10am-12pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-2pm-4pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-4pm-6pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-6pm-8pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-8pm-10pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-6am-8am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-8am-10am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-10am-12pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-2pm-4pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-4pm-6pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-6pm-8pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("JUEVES-8pm-10pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-6am-8am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-8am-10am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-10am-12pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-2pm-4pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-4pm-6pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-6pm-8pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("VIERNES-8pm-10pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-6am-8am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-8am-10am");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-10am-12pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-2pm-4pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-4pm-6pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-6pm-8pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("SABADO-8pm-10pm");
            horarioAux.setIntencidadSemanal(2);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-6am-8am");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-8am-10am");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-10am-12pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-2pm-4pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-4pm-6pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-6pm-8pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("LUNES-MIERCOLES-8pm-10pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-6am-8am");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-8am-10am");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-10am-12pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-2pm-4pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-4pm-6pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-6pm-8pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MARTES-JUEVES-8pm-10pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-6am-8am");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-8am-10am");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-10am-12pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-2pm-4pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-4pm-6pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-6pm-8pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
            horarioAux = new HorarioProfesorVO();
            horarioAux.setDiaHora("MIERCOLES-VIERNES-8pm-10pm");
            horarioAux.setIntencidadSemanal(4);
            horarios.add(horarioAux);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return horarios;
    }

}
